on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - qa
          - staging
          - prod

      image_tag:
        description: "Docker image tag"
        required: true
        type: string

      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - deploy
          - rollback

      dry_run:
        description: "Perform dry run"
        required: true
        type: boolean
        default: false
